apiVersion: v1
kind: Service

metadata:
  name: gva-web-service
  namespace: gva

spec:
  type: NodePort

  selector:
    app: gva-web

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080