apiVersion: apps/v1
kind: Deployment

metadata:
  name: web-deployment
  namespace: {{ .Values.namespace}}

spec:
  replicas: {{ .Values.web.replicas}}

  selector:
    matchLabels:
      app: gva-web

  template:
    metadata:
      labels:
        app: gva-web

    spec:
      containers:
        - name: gva-web
          image: {{ .Values.web.image}}
          imagePullPolicy: {{ .Values.web.imagePullPolicy}}

          ports:
          - name: http
            containerPort: {{ .Values.web.port}}
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP

            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3

          # 就绪探针
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP

            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3